# Header
menu:
  主页: /
  所有文章: /archives
  #随笔: /tags/随笔
  #标签: /tags
  关于&留言: /about
  #相册: /photo
  #留言板: /msg          #hexo new page "msg"

# SubNav
subnav:
  github: "https://github.com/poetries"
  weibo: "http://weibo.com/poetries1"
  mail: "p@poetries.top"
  rss: /atom.xml
  jianshu: "http://www.jianshu.com/users/94077fcddfc0/latest_articles"
  #zhihu: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
#google_analytics: ''
baidu_tongji: true
favicon: /favicon.jpg

#你的头像url
avatar: /img/me.JPG
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: "poetry"
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  #Litten: http://litten.github.io/
  #YeHBeats: http://www.yehbeats.com/
  

#是否统计网站访问次数
counter: true

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 专注于前端

#是否开启打赏功能
donate: true
#打赏文案
donate_message: Enjoy it ? Donate me !  欣赏此文？求鼓励，求支持！