# Blog info
blog_name: Poetry's Blog
slogan: Choose a gesture to allow yourself to live irreplaceable
url: http://blog.poetries.top

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: poetries,前端,设计,Hexo主题,前端开发,用户体验,设计,frontend,design,nodejs,JavaScript

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  #- name: Project
    #url: /project/
    #target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/poetries
    target_blank: true
  - name: Jianshu
    url: http://www.jianshu.com/users/94077fcddfc0/latest_articles
    target_blank: true
  - name: Handbook
    url: http://blog.poetries.top/handbook
    target_blank: true
  - name: Notes
    url: http://blog.poetries.top/js-knowledge-note
    target_blank: true
  - name: Interview
    url: http://blog.poetries.top/FE-Interview-Questions
    target_blank: true
  - name: Life
    url: http://life.poetries.top
    target_blank: true
    
# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /categories/
    target_blank: false
  - name: 标签
    url: /tags/
    target_blank: false
  #- name: 友链
    #url: /link/
    #target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  #- name: 留言
    #url: /guestbook/
    #target_blank: false
  #- name: 搜索
    #url: /search/
    #target_blank: false # 在新页面打开
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 p@poetries.top


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 支持一下
  tip: 扫一扫，支持poetries
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/weixin.jpg
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/zhifubao.jpg




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
#personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 

# Comment service
#disqus_shortname: poetry
#duoshuo_shortname: poetry


# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "poetries，1993."
    - "热爱前端,专注于前端开发"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@poetries"
    text_value_url: https://github.com/poetries
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@poetries"
    text_value_url: http://weibo.com/u/poetries1
  - type: mail
    icon: icon-mail
    text_key: Email
    text_value: "p@poetries.top"
  - type: location
    icon: icon-location
    text_value: 广东深圳
# 友链

link:
# - name: 织网
    #info: 身体和灵魂，总有一个在路上
    #url: http://zheng-ji.info/
    #avatar: https://avatars3.githubusercontent.com/u/1414745?v=3&s=100


project:
  - type: personal
    name: drawing-board
    url: http://blog.poetries.top/drawing-board
    intro: canvas画图板
  - type: personal
    name: music-player
    url: http://blog.poetries.top/music-player
    intro: 一个H5音频播放器
 
